import java.util.Objects;

public class Edge {
    //Private data members
    private int id;
    private Vertex end1;
    private Vertex end2;
    private int distance;

    //Default Constructor
    public Edge(int id, Vertex end1, Vertex end2, int distance)
    {
        this.id = id;
        this.end1 = end1;
        this.end2 = end2;
        this.distance = distance;
    }

    //Setters and getters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Vertex getEnd1() {
        return end1;
    }

    public void setEnd1(Vertex end1) {
        this.end1 = end1;
    }

    public Vertex getEnd2() {
        return end2;
    }

    public void setEnd2(Vertex end2) {
        this.end2 = end2;
    }

    public int getDistance() {
        return distance;
    }

    public void setDistance(int distance) {
        this.distance = distance;
    }

    //These methods are auto generated by intelliJ Idea to override the equals and hashCode functions
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Edge edge = (Edge) o;
        return id == edge.id &&
                distance == edge.distance &&
                Objects.equals(end1, edge.end1) &&
                Objects.equals(end2, edge.end2);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id, end1, end2, distance);
    }

    //To string method
    @Override
    public String toString() {
        return "Edge{" +
                "id=" + id +
                ", end1=" + end1 +
                ", end2=" + end2 +
                ", distance=" + distance +
                '}';
    }
}
