import java.util.Objects;

public class Vertex {
    //Private data members
    private String name;
    private int id;

    //Default Contructor
    public Vertex(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    //Setters and Getters
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    //Override functions that are auto generated by intelliJ Idea

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Vertex vertex = (Vertex) o;
        return id == vertex.id &&
                Objects.equals(name, vertex.name);
    }

    @Override
    public int hashCode() {

        return Objects.hash(name, id);
    }

    //To string method

    @Override
    public String toString() {
        return "Vertex{" +
                "name='" + name + '\'' +
                ", id=" + id +
                '}';
    }
}
